Melhorando README do projeto
betrybe/sd-0x-block14-project-movie-card-library-crud pull request #13
Opened 2020-09-03 13:37 UTC by johnatas-henrique

2020-09-03 13:46 UTC, douglas-he commented on README.md
>  Este repositório já contém um _template_ com um App React criado e configurado. Após clonar o projeto e instalar as dependências (mais sobre isso abaixo), você não precisará realizar nenhuma configur
```suggestion
Este repositório já contém um _template_ com um App React criado e configurado. Após clonar o projeto e instalar as dependências (mais sobre isso em "ANTES DE COMEÇAR A DESENVOLVER"), você não precisará realizar nenhuma configuração adicional. Todos os componentes estritamente necessários para finalizar o projeto já estão criados, mas você pode adicionar outros se julgar necessário. Você deverá complementar estes componentes de forma a satisfazer os requisitos listados na próxima seção.
```

2020-09-03 13:49 UTC, douglas-he requested changes
Seria bom alterar as partes sobre github, assim como o nome do repositório para a nova convenção de nomes de projetos

2020-09-03 16:50 UTC, Caciquez approved these changes

2020-09-04 13:30 UTC, douglas-he approved these changes

2020-09-09 15:55 UTC, merged